name: Utc App CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions:
    id-token: write
    contents: read

env:
  PYTHON_VERSION: "3.14"
  IMAGE_NAME: portfolio
  AWs_REGION: us-east-1
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  ECR_REPO:  ${{ secrets.ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/dev/portfolio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest test.py
      - name: configure AWScredentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: ${{ secrets. ROLE_ARN }} 
            aws-region: ${{ env.AWs_REGION }} 
      - name: login to amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
            
      - name: Build Docker image
        run: 
          docker build -t ${{env. IMAGE_NAME}} .
       # tag Docker image  for ECR

      - name: Tag Docker image
        run: docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.ECR_REPO }}:latest

      # scan Docker Image with Trivy

      - name: scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref:${{env.ECR_REPO }}: latest
          format: table
          exit-code: '1' # fail workflow on critical/high  vulnerabilities
          serverity: CRITICAL, HIGH

    # Push docker image to ECR
      - name: push docker image to amazon ECR
        run: 
          docker push ${{env.ECR_REPO}}
    
      - name: check credentials 
        run: aws s3 ls






























